### ISSUE TITLE
Gulp throws an error: unrecognized input on line 744

### ISSUE THREAD

**Issue by sahat** [t4t5/sweetalert#354]
For some reason gulp and gulp-less does not like IE9 fixes on line 744:

```
Message:
    Unrecognised input in file /Users/sahat/Developer/app/app/stylesheets/lib/sweetalert.less line no. 744
Details:
    type: Parse
    filename: /Users/sahat/Developer/app/app/stylesheets/lib/sweetalert.less
    index: 17808
    line: 744
    callLine: NaN
    callExtract: undefined
    column: 31
    extract: .sweet-alert .sa-icon.sa-error .sa-line.sa-left {,  -ms-transform: rotate(45deg) \9; },
    lineNumber: 744
    fileName: /Users/sahat/Developer/app/app/stylesheets/lib/sweetalert.less
```
