### ISSUE TITLE
Vertical scroller

### ISSUE THREAD

**Issue by gaurapanasenko** [t4t5/sweetalert#521]
Hi. I want share how i did vertical scrolling.

``` css
.sweet-alert {
    box-sizing : border-box;
    max-height : 100% !important;
    overflow-y : auto !important;
    padding : 0 17px 17px !important;
    width : 512px;
}
.sweet-alert:before {
    content : "";
    display : block;
    height : 17px;
    width : 0;
}
```

``` javascript
$(window).resize(function(){
    $(".sweet-alert").css("margin-top",-$(".sweet-alert").outerHeight()/2);
});
```
