### ISSUE TITLE
sweetalert.css "\9" what it means?

### ISSUE THREAD

**Issue by mqliutie** [t4t5/sweetalert#585]
from line : 733 to line : 747

``` css
.sweet-alert .sa-icon.sa-error .sa-line.sa-left {
  -ms-transform: rotate(45deg) \9; } //line : 734

.sweet-alert .sa-icon.sa-error .sa-line.sa-right {
  -ms-transform: rotate(-45deg) \9; } // line : 737

/* Success icon */
.sweet-alert .sa-icon.sa-success {
  border-color: transparent\9; } // line : 741

.sweet-alert .sa-icon.sa-success .sa-line.sa-tip {
  -ms-transform: rotate(45deg) \9; } // line : 744

.sweet-alert .sa-icon.sa-success .sa-line.sa-long {
  -ms-transform: rotate(-45deg) \9; } //line : 747
```

**`\9`** plays an important role?  

If I delete **`\9`** it works well.

If not the error will appear

```
app.3f565b8….js?3f565b8…:15702 ./~/css-loader!./~/less-loader!./~/sweetalert/dist/sweetalert.css
Module build failed: Unrecognised input
 @ /Users/missl/webpack-lazyload-angular/node_modules/sweetalert/dist/sweetalert.css (line 734, column 31)
 near lines:
   .sweet-alert .sa-icon.sa-error .sa-line.sa-left {
     -ms-transform: rotate(45deg) \9; }

Error: Unrecognised input
 @ /Users/missl/webpack-lazyload-angular/node_modules/sweetalert/dist/sweetalert.css (line 734, column 31)
 near lines:
   .sweet-alert .sa-icon.sa-error .sa-line.sa-left {
     -ms-transform: rotate(45deg) \9; }
 at formatLessRenderError (/Users/missl/webpack-lazyload-angular/node_modules/less-loader/index.js:165:12)
    at /Users/missl/webpack-lazyload-angular/node_modules/less-loader/index.js:68:19
    at /Users/missl/webpack-lazyload-angular/node_modules/less/lib/less/render.js:26:35
    at /Users/missl/webpack-lazyload-angular/node_modules/less/lib/less/parse.js:62:33
    at Object.finish [as _finish] (/Users/missl/webpack-lazyload-angular/node_modules/less/lib/less/parser/parser.js:180:28)
    at Object.ImportVisitor._onSequencerEmpty (/Users/missl/webpack-lazyload-angular/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
    at ImportSequencer.tryRun (/Users/missl/webpack-lazyload-angular/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
    at Object.ImportVisitor.run (/Users/missl/webpack-lazyload-angular/node_modules/less/lib/less/visitors/import-visitor.js:29:25)
    at Object.Parser.parse (/Users/missl/webpack-lazyload-angular/node_modules/less/lib/less/parser/parser.js:189:22)
    at Object.parse (/Users/missl/webpack-lazyload-angular/node_modules/less/lib/less/parse.js:61:18)
    at Object.render (/Users/missl/webpack-lazyload-angular/node_modules/less/lib/less/render.js:25:18)
    at Object.module.exports (/Users/missl/webpack-lazyload-angular/node_modules/less-loader/index.js:62:7)
 @ ./~/sweetalert/dist/sweetalert.css 4:14-100 13:2-17:4 14:20-106
```

I don't know the error is leaded by **`\9`** or `less-loader` ?
