### ISSUE TITLE
Sweetalert in IE 10

### ISSUE THREAD

**Issue by mohammad-shadmehr** [t4t5/sweetalert#863]
I am using Sweetalert version 2.0.8 and it works perfect in Chrome, Edge, IE 11 but IE 10. The problem is that when it pops up and user click any button on it (OK,Confirm, Cancel) it hides the popup but also freezes the entire screen user wont be able to click anywhere on the page!

**Comment by jbeliezVega** [comment]
Same here !

**Comment by skittlyoaten** [comment]
"Uses ES6, and Does not (and never will) support IE10 or lower" should be at the top of the description.  Unfortunately for many, IE10 is not dead yet, and metrics tell us too many customers use it to ignore.

**Comment by lionralfs** [comment]
Hey guys,

I've realized that IE<11 [does not support](https://caniuse.com/#feat=pointer-events) the `pointer-events` CSS property. We're using it to prevent the hidden modal (which is still overlaying the entire page) from being clickable. A workaround would be to use the `visibility` property instead, which has the same effect.

So we either change all occurrences of `pointer-events` in the codebase to use `visibility` (so we can still support IE<11), or you could try overriding sweetalert's CSS with this snippet whenever you detect IE<11:

```css
body .swal-overlay {
  visibility: hidden;
}

body .swal-overlay--show-modal {
  visibility: visible;
}

body .swal-button__loader {
  visibility: hidden;
}

body .swal-overlay--show-modal .swal-modal {
  visibility: visible;
}

body .swal-modal {
  visibility: hidden;
}
```

@t4t5 what are your thoughts? I haven't really tested this much in other browsers other than IE10.
