### ISSUE TITLE
Success icon bug on dark backgrounds

### ISSUE THREAD

**Issue by hamid0740** [t4t5/sweetalert#969]
Hello, as you can see in the gif below, in the dark backgrounds, the success icon will have a little problem. If you can please make this icon customizable, too.
![Success-icon-bug](https://user-images.githubusercontent.com/55584608/123483346-cdca9980-d61b-11eb-8275-1b7fa1488fca.gif)

I should also mention that the other icons including: info, error & warning do not have any problems with dark backgrounds and work properly.

**Comment by imkuroneko** [comment]
Add this on your CSS file for handle that situation

```css
.swal-icon--success__hide-corners, .swal-icon--success:after, .swal-icon--success:before {
    background: #5a5a5a; /* your color here */
}
```
